#!/bin/sh

now=$(date +"%s_%Y-%m-%d")
pw=$(<"/run/secrets/db_backup_pw")
/usr/bin/mysqldump --opt -h ${MYSQL_HOST} -u ${MYSQL_BACKUPER_USER} -p${pw} ${MYSQL_DATABASE} > "/backup/${now}_${MYSQL_DATABASE}.sql"
