#!/bin/bash
set -e

mysql -u root -p$MYSQL_ROOT_PASSWORD <<EOSQL

CREATE USER IF NOT EXISTS '$MYSQL_BACKUPER_USER'@'%' IDENTIFIED WITH mysql_native_password BY '$MYSQL_BACKUPER_PASSWORD';
GRANT ALL PRIVILEGES ON $MYSQL_DATABASE.* TO '$MYSQL_BACKUPER_USER'@'%' WITH GRANT OPTION;

FLUSH PRIVILEGES;
EOSQL
