SET @MYSQL_ROOT_PASSWORD:='$MYSQL_ROOT_PASSWORD';
SET @MYSQL_PASSWORD:='$MYSQL_PASSWORD';
SET @MYSQL_USER:='$MYSQL_USER';
SET @MYSQL_DATABASE:='$MYSQL_DATABASE';
ALTER USER 'root'@'%' IDENTIFIED BY '@MYSQL_ROOT_PASSWORD';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%';
FLUSH PRIVILEGES;

CREATE DATABASE IF NOT EXISTS virtd;
USE virtd;
CREATE USER IF NOT EXISTS '@MYSQL_USER'@'%' WITH mysql_native_password  BY '@MYSQL_PASSWORD';
GRANT ALL PRIVILEGES ON 'virtd'.* TO '@MYSQL_USER'@'%';
FLUSH PRIVILEGES;
